# Recipe in rattler-build format.
# See https://prefix-dev.github.io/rattler-build/latest/
# Before building this recipe, build the conda
# packages for "deadline" and "openjd-adaptor-runtime" dependencies.
# Find these recipes for building the packages at :
# https://github.com/aws-deadline/deadline-cloud-samples/tree/mainline/conda_recipes

context:
  version: "0.8.8"

package:
  name: cinema4d-openjd
  version: ${{ version }}

# Use S3-hosted source for testing local changes
source:
  url: s3://deadlinecloud-job-attachments-vaish-test-monitor/source/deadline_cloud_for_cinema_4d-0.8.5.post12+g1cb6a50ab.tar.gz

build:
  number: 0
  script:
    - python -m pip install . -vv --no-deps
    - if: linux
      then:
        - chmod +x $PREFIX/lib/python3.13/site-packages/deadline/cinema4d_adaptor/Cinema4DAdaptor/adaptor.sh || true

requirements:
  host:
    - python
    - hatchling
    - hatch-vcs
    - pip
  run:
    - python
    - deadline >=0.51.1,<0.54
    - openjd-adaptor-runtime 0.9.*

tests:
- python:
    imports:
      - deadline.cinema4d_adaptor
- requirements:
    run:
      - pip
  script:
    - pip check
# This doesn't work on Windows, possibly a rattler-build bug since cinema4d-openjd.exe is in $PREFIX/Scripts
#    - cinema4d-openjd --help

about:
  summary: AWS Deadline Cloud for Cinema 4D
  homepage: https://github.com/aws-deadline/deadline-cloud-for-cinema-4d
  license: Apache-2.0
  license_file:
    - LICENSE
    - NOTICE
